2025-04-11 20:14:49,074 INFO: Session data: reset_email=babywho308@gmail.com, reset_otp=698982, reset_expiry=1744434753.054662 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:228]
2025-04-11 20:14:49,077 INFO: Received OTP: 200845 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:241]
2025-04-11 20:14:49,077 INFO: Stored OTP: 698982 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:242]
2025-04-11 20:14:49,077 ERROR: OTP mismatch. Received: '200845', Stored: '698982' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:264]
2025-04-11 20:14:49,082 INFO: Session data: reset_email=babywho308@gmail.com, reset_otp=698982, reset_expiry=1744434753.054662 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:228]
2025-04-11 20:17:28,309 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:17:36,015 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:17:48,409 INFO: Password reset requested for babywho308@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:209]
2025-04-11 20:18:08,592 INFO: Received Supabase token for verification: 125814 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:227]
2025-04-11 20:18:09,022 ERROR: Password reset verification error: Only an email address or phone number should be provided on verify [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:258]
2025-04-11 20:21:28,806 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:21:36,507 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:21:50,158 INFO: Password reset requested for babywho308@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:209]
2025-04-11 20:22:46,032 INFO: Received Supabase token for verification: 933888 [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:228]
2025-04-11 20:22:46,591 INFO: Supabase token verified successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:246]
2025-04-11 20:23:00,698 INFO: User babywho308@gmail.com logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:43]
2025-04-11 20:27:27,657 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:27:28,095 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:27:36,155 WARNING: Supabase logout failed for user babywho308@gmail.com: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:176]
2025-04-11 20:27:36,157 INFO: User babywho308@gmail.com logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:179]
2025-04-11 20:27:46,207 INFO: User babywho308@gmail.com logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:43]
2025-04-11 20:32:47,583 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:32:47,992 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:33:38,726 INFO: User Vincent.dangelo@gilmour.org logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:43]
2025-04-11 20:39:45,504 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:39:49,054 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:47:02,504 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:48:04,154 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 20:50:50,429 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:29]
2025-04-11 20:52:43,574 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:29]
2025-04-11 20:53:06,098 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:29]
2025-04-11 20:53:06,499 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:29]
2025-04-11 20:55:10,208 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:00:42,048 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:00:46,582 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:00:49,062 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:01:16,104 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:01:28,452 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:01:28,832 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:02:23,508 ERROR: Error creating blog post: supabase_key is required [in /Users/d_angel/Access_Point_V3/app/routes/blog.py:119]
2025-04-11 21:13:08,137 ERROR: Error creating blog post: supabase_key is required [in /Users/d_angel/Access_Point_V3/app/routes/blog.py:119]
2025-04-11 21:13:31,155 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:13:31,564 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:14:10,539 ERROR: Error creating blog post: supabase_key is required [in /Users/d_angel/Access_Point_V3/app/routes/blog.py:119]
2025-04-11 21:14:31,956 ERROR: Error creating blog post: supabase_key is required [in /Users/d_angel/Access_Point_V3/app/routes/blog.py:119]
2025-04-11 21:14:58,691 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:17:38,880 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:17:41,480 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:18:16,951 ERROR: Error creating blog post: supabase_key is required [in /Users/d_angel/Access_Point_V3/app/routes/blog.py:119]
2025-04-11 21:22:09,029 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:22:23,819 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:22:43,793 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:22:56,584 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-11 21:23:18,701 ERROR: Supabase storage error: {'statusCode': 403, 'error': Unauthorized, 'message': new row violates row-level security policy} [in /Users/d_angel/Access_Point_V3/app/utils/storage.py:41]
2025-04-11 21:23:18,702 ERROR: Error in upload_image_to_supabase: {'statusCode': 403, 'error': Unauthorized, 'message': new row violates row-level security policy} [in /Users/d_angel/Access_Point_V3/app/utils/storage.py:45]
2025-04-17 20:07:16,822 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:14:09,233 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:14:32,560 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:16:38,261 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:17:54,755 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:18:01,454 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:18:01,859 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:18:14,749 ERROR: Login error for user babywho308@gmail.com: Invalid login credentials [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:52]
2025-04-17 20:18:22,683 INFO: User babywho308@gmail.com logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:43]
2025-04-17 20:19:11,843 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:27]
2025-04-17 20:19:39,918 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:28]
