2025-04-09 13:52:32,411 INFO: User accesspointfoundation@gmail.com logged out successfully [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/routes/auth.py:177]
2025-04-09 13:52:40,105 ERROR: Login error for user sethrobles04@gmail.com: Invalid login credentials [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/routes/auth.py:50]
2025-04-09 13:56:58,756 ERROR: Login error for user sethrobles04@gmail.com: Invalid login credentials [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/routes/auth.py:50]
2025-04-09 13:57:06,522 ERROR: Login error for user sethrobles04@gmail.com: Invalid login credentials [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/routes/auth.py:50]
2025-04-09 13:57:08,438 INFO: User accesspointfoundation@gmail.com logged in successfully [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/routes/auth.py:41]
2025-04-09 17:30:00,491 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
2025-04-09 17:30:00,992 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
2025-04-09 17:45:41,127 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
2025-04-09 17:46:27,333 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
2025-04-10 22:29:24,957 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
2025-04-10 22:29:25,581 INFO: Access Point startup [in /Users/sethrobles/Documents/Projects/accesspoint/AccessPoint_V3/app/__init__.py:27]
